// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: net_common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NetMsg {

  /// <summary>Holder for reflection information generated from net_common.proto</summary>
  public static partial class NetCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for net_common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBuZXRfY29tbW9uLnByb3RvEgZOZXRNc2ciRAoOTmV0TXNnRW52ZWxvcGUS",
            "IQoIbXNnX3R5cGUYASABKA4yDy5OZXRNc2cuTXNnVHlwZRIPCgdwYXlsb2Fk",
            "GAIgASgMKp8CCglFcnJvckNvZGUSDgoKRVJST1JfTk9ORRAAEhMKDkVSUk9S",
            "X0lOVEVSTkFMEOgHEhYKEUVSUk9SX1VTRVJfRVhJU1RTEOkHEhwKF0VSUk9S",
            "X1dST05HX0NSRURFTlRJQUxTEOoHEhcKEkVSUk9SX1VOQVVUSE9SSVpFRBDr",
            "BxIbChZFUlJPUl9QTEFZRVJfTk9UX0ZPVU5EEOwHEhwKF0VSUk9SX1BST0ZJ",
            "TEVfTk9UX0ZPVU5EEO0HEhYKEUVSUk9SX05PVF9JTl9ST09NEO4HEhkKFEVS",
            "Uk9SX1JPT01fTk9UX0ZPVU5EEO8HEhQKD0VSUk9SX1JPT01fRlVMTBDwBxIa",
            "ChVFUlJPUl9BTFJFQURZX0lOX1JPT00Q8QcquwMKB01zZ1R5cGUSDAoITVNH",
            "X05PTkUQABIUChBNU0dfUExBWUVSX0lOUFVUEAESEgoOTVNHX0ZSQU1FX0RB",
            "VEEQAhIRCg1NU0dfTUFJTF9QVVNIEAMSHAoYTVNHX0FDVElWSVRZX1JFV0FS",
            "RF9QVVNIEAQSFQoRTVNHX1VEUF9MT0dJTl9SRVEQBRIWChJNU0dfVURQX0xP",
            "R0lOX1JFU1AQBhIQCgxNU0dfUk9PTV9SRVEQBxIRCg1NU0dfUk9PTV9SRVNQ",
            "EAgSFwoTTVNHX1JPT01fU1RBVEVfUFVTSBAJEhYKEk1TR19MRUFWRV9ST09N",
            "X1JFURAKEhcKE01TR19MRUFWRV9ST09NX1JFU1AQCxIRCg1NU0dfTUFUQ0hf",
            "UkVREAwSEgoOTVNHX01BVENIX1JFU1AQDRIRCg1NU0dfUkVBRFlfUkVREA4S",
            "EgoOTVNHX1JFQURZX1JFU1AQDxIXChNNU0dfU1RBUlRfR0FNRV9QVVNIEBAS",
            "FAoQTVNHX0dBTUVfRU5EX1JFURAREhUKEU1TR19HQU1FX0VORF9SRVNQEBIS",
            "FQoRTVNHX0dBTUVfRU5EX1BVU0gQE2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NetMsg.ErrorCode), typeof(global::NetMsg.MsgType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NetMsg.NetMsgEnvelope), global::NetMsg.NetMsgEnvelope.Parser, new[]{ "MsgType", "Payload" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 错误码（0 = 成功，非 0 = 失败）
  /// 约定：所有 Resp 消息的 error_code 固定放在 field 1，业务字段从 field 2 往后排，
  ///       这样新增字段直接往下追加，无需改动已有字段号
  /// </summary>
  public enum ErrorCode {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("ERROR_NONE")] ErrorNone = 0,
    /// <summary>
    /// 服务器内部错误（含响应非 proto 等异常情况）
    /// </summary>
    [pbr::OriginalName("ERROR_INTERNAL")] ErrorInternal = 1000,
    /// <summary>
    /// 用户名已存在
    /// </summary>
    [pbr::OriginalName("ERROR_USER_EXISTS")] ErrorUserExists = 1001,
    /// <summary>
    /// 用户名或密码错误
    /// </summary>
    [pbr::OriginalName("ERROR_WRONG_CREDENTIALS")] ErrorWrongCredentials = 1002,
    /// <summary>
    /// 未授权（未带 token 或 token 无效）
    /// </summary>
    [pbr::OriginalName("ERROR_UNAUTHORIZED")] ErrorUnauthorized = 1003,
    /// <summary>
    /// 玩家不存在
    /// </summary>
    [pbr::OriginalName("ERROR_PLAYER_NOT_FOUND")] ErrorPlayerNotFound = 1004,
    /// <summary>
    /// 养成数据不存在
    /// </summary>
    [pbr::OriginalName("ERROR_PROFILE_NOT_FOUND")] ErrorProfileNotFound = 1005,
    /// <summary>
    /// 不在房间内（建房/加入前须先通过 UDP 认证）
    /// </summary>
    [pbr::OriginalName("ERROR_NOT_IN_ROOM")] ErrorNotInRoom = 1006,
    /// <summary>
    /// 加入的房间不存在
    /// </summary>
    [pbr::OriginalName("ERROR_ROOM_NOT_FOUND")] ErrorRoomNotFound = 1007,
    /// <summary>
    /// 房间已满
    /// </summary>
    [pbr::OriginalName("ERROR_ROOM_FULL")] ErrorRoomFull = 1008,
    /// <summary>
    /// 已在房间中（需先退出）
    /// </summary>
    [pbr::OriginalName("ERROR_ALREADY_IN_ROOM")] ErrorAlreadyInRoom = 1009,
  }

  /// <summary>
  /// 全局消息类型（UDP 信封 msg_type 用）
  /// 编号全局唯一，由编译器保证不重复；新增消息在此追加枚举值即可
  /// </summary>
  public enum MsgType {
    /// <summary>
    /// 占位
    /// </summary>
    [pbr::OriginalName("MSG_NONE")] MsgNone = 0,
    /// <summary>
    /// 玩家操作（客户端->服务器）
    /// </summary>
    [pbr::OriginalName("MSG_PLAYER_INPUT")] MsgPlayerInput = 1,
    /// <summary>
    /// 帧数据（服务器->客户端）
    /// </summary>
    [pbr::OriginalName("MSG_FRAME_DATA")] MsgFrameData = 2,
    /// <summary>
    /// 邮件推送
    /// </summary>
    [pbr::OriginalName("MSG_MAIL_PUSH")] MsgMailPush = 3,
    /// <summary>
    /// 活动结算推送
    /// </summary>
    [pbr::OriginalName("MSG_ACTIVITY_REWARD_PUSH")] MsgActivityRewardPush = 4,
    /// <summary>
    /// UDP 连接认证请求（客户端->GameServer，带 JWT token）
    /// </summary>
    [pbr::OriginalName("MSG_UDP_LOGIN_REQ")] MsgUdpLoginReq = 5,
    /// <summary>
    /// UDP 连接认证回复（GameServer->客户端）
    /// </summary>
    [pbr::OriginalName("MSG_UDP_LOGIN_RESP")] MsgUdpLoginResp = 6,
    /// <summary>
    /// 房间请求（客户端->服务器：无 room_id=创建，有=加入）
    /// </summary>
    [pbr::OriginalName("MSG_ROOM_REQ")] MsgRoomReq = 7,
    /// <summary>
    /// 房间请求回复（服务器->客户端）
    /// </summary>
    [pbr::OriginalName("MSG_ROOM_RESP")] MsgRoomResp = 8,
    /// <summary>
    /// 房间状态推送（服务器->房间内所有成员：成员列表变化）
    /// </summary>
    [pbr::OriginalName("MSG_ROOM_STATE_PUSH")] MsgRoomStatePush = 9,
    /// <summary>
    /// 退出房间请求（客户端->服务器）
    /// </summary>
    [pbr::OriginalName("MSG_LEAVE_ROOM_REQ")] MsgLeaveRoomReq = 10,
    /// <summary>
    /// 退出房间回复（服务器->客户端）
    /// </summary>
    [pbr::OriginalName("MSG_LEAVE_ROOM_RESP")] MsgLeaveRoomResp = 11,
    /// <summary>
    /// 匹配请求（客户端->服务器：开始/取消）
    /// </summary>
    [pbr::OriginalName("MSG_MATCH_REQ")] MsgMatchReq = 12,
    /// <summary>
    /// 匹配回复（服务器->客户端：受理回执/撮合成功）
    /// </summary>
    [pbr::OriginalName("MSG_MATCH_RESP")] MsgMatchResp = 13,
    /// <summary>
    /// 就绪请求（客户端->服务器，房间内成员）
    /// </summary>
    [pbr::OriginalName("MSG_READY_REQ")] MsgReadyReq = 14,
    /// <summary>
    /// 就绪回复（服务器->客户端）
    /// </summary>
    [pbr::OriginalName("MSG_READY_RESP")] MsgReadyResp = 15,
    /// <summary>
    /// 开战推送（服务器->房间全员：起始帧+随机种子）
    /// </summary>
    [pbr::OriginalName("MSG_START_GAME_PUSH")] MsgStartGamePush = 16,
    /// <summary>
    /// 游戏结束上报（客户端->服务器：本地模拟判定结束后）
    /// </summary>
    [pbr::OriginalName("MSG_GAME_END_REQ")] MsgGameEndReq = 17,
    /// <summary>
    /// 游戏结束回执（服务器->客户端）
    /// </summary>
    [pbr::OriginalName("MSG_GAME_END_RESP")] MsgGameEndResp = 18,
    /// <summary>
    /// 游戏结束推送（服务器->房间全员：结束帧+结果）
    /// </summary>
    [pbr::OriginalName("MSG_GAME_END_PUSH")] MsgGameEndPush = 19,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 消息信封：所有 UDP 消息统一包在这一层，首字段标识消息类型，payload 承载具体消息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NetMsgEnvelope : pb::IMessage<NetMsgEnvelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NetMsgEnvelope> _parser = new pb::MessageParser<NetMsgEnvelope>(() => new NetMsgEnvelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NetMsgEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetMsg.NetCommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMsgEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMsgEnvelope(NetMsgEnvelope other) : this() {
      msgType_ = other.msgType_;
      payload_ = other.payload_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMsgEnvelope Clone() {
      return new NetMsgEnvelope(this);
    }

    /// <summary>Field number for the "msg_type" field.</summary>
    public const int MsgTypeFieldNumber = 1;
    private global::NetMsg.MsgType msgType_ = global::NetMsg.MsgType.MsgNone;
    /// <summary>
    /// 消息类型（见 MsgType 枚举）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMsg.MsgType MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 2;
    private pb::ByteString payload_ = pb::ByteString.Empty;
    /// <summary>
    /// 具体消息的 proto 序列化字节
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NetMsgEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NetMsgEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgType != other.MsgType) return false;
      if (Payload != other.Payload) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgType != global::NetMsg.MsgType.MsgNone) hash ^= MsgType.GetHashCode();
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MsgType != global::NetMsg.MsgType.MsgNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MsgType != global::NetMsg.MsgType.MsgNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MsgType != global::NetMsg.MsgType.MsgNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
      }
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NetMsgEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.MsgType != global::NetMsg.MsgType.MsgNone) {
        MsgType = other.MsgType;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MsgType = (global::NetMsg.MsgType) input.ReadEnum();
            break;
          }
          case 18: {
            Payload = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MsgType = (global::NetMsg.MsgType) input.ReadEnum();
            break;
          }
          case 18: {
            Payload = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
