// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: net_common.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NetMsg {

  /// <summary>Holder for reflection information generated from net_common.proto</summary>
  public static partial class NetCommonReflection {

    #region Descriptor
    /// <summary>File descriptor for net_common.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetCommonReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBuZXRfY29tbW9uLnByb3RvEgZOZXRNc2ciRAoOTmV0TXNnRW52ZWxvcGUS",
            "IQoIbXNnX3R5cGUYASABKA4yDy5OZXRNc2cuTXNnVHlwZRIPCgdwYXlsb2Fk",
            "GAIgASgMKroBCglFcnJvckNvZGUSDgoKRVJST1JfTk9ORRAAEhMKDkVSUk9S",
            "X0lOVEVSTkFMEOgHEhYKEUVSUk9SX1VTRVJfRVhJU1RTEOkHEhwKF0VSUk9S",
            "X1dST05HX0NSRURFTlRJQUxTEOoHEhcKEkVSUk9SX1VOQVVUSE9SSVpFRBDr",
            "BxIbChZFUlJPUl9QTEFZRVJfTk9UX0ZPVU5EEOwHEhwKF0VSUk9SX1BST0ZJ",
            "TEVfTk9UX0ZPVU5EEO0HKqABCgdNc2dUeXBlEgwKCE1TR19OT05FEAASFAoQ",
            "TVNHX1BMQVlFUl9JTlBVVBABEhIKDk1TR19GUkFNRV9EQVRBEAISEQoNTVNH",
            "X01BSUxfUFVTSBADEhwKGE1TR19BQ1RJVklUWV9SRVdBUkRfUFVTSBAEEhUK",
            "EU1TR19VRFBfTE9HSU5fUkVREAUSFQoRTVNHX1VEUF9MT0dJTl9BQ0sQBmIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NetMsg.ErrorCode), typeof(global::NetMsg.MsgType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NetMsg.NetMsgEnvelope), global::NetMsg.NetMsgEnvelope.Parser, new[]{ "MsgType", "Payload" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 错误码（0 = 成功，非 0 = 失败）
  /// 约定：所有 Resp 消息的 error_code 固定放在 field 1，业务字段从 field 2 往后排，
  ///       这样新增字段直接往下追加，无需改动已有字段号
  /// </summary>
  public enum ErrorCode {
    /// <summary>
    /// 成功
    /// </summary>
    [pbr::OriginalName("ERROR_NONE")] ErrorNone = 0,
    /// <summary>
    /// 服务器内部错误（含响应非 proto 等异常情况）
    /// </summary>
    [pbr::OriginalName("ERROR_INTERNAL")] ErrorInternal = 1000,
    /// <summary>
    /// 用户名已存在
    /// </summary>
    [pbr::OriginalName("ERROR_USER_EXISTS")] ErrorUserExists = 1001,
    /// <summary>
    /// 用户名或密码错误
    /// </summary>
    [pbr::OriginalName("ERROR_WRONG_CREDENTIALS")] ErrorWrongCredentials = 1002,
    /// <summary>
    /// 未授权（未带 token 或 token 无效）
    /// </summary>
    [pbr::OriginalName("ERROR_UNAUTHORIZED")] ErrorUnauthorized = 1003,
    /// <summary>
    /// 玩家不存在
    /// </summary>
    [pbr::OriginalName("ERROR_PLAYER_NOT_FOUND")] ErrorPlayerNotFound = 1004,
    /// <summary>
    /// 养成数据不存在
    /// </summary>
    [pbr::OriginalName("ERROR_PROFILE_NOT_FOUND")] ErrorProfileNotFound = 1005,
  }

  /// <summary>
  /// 全局消息类型（UDP 信封 msg_type 用）
  /// 编号全局唯一，由编译器保证不重复；新增消息在此追加枚举值即可
  /// </summary>
  public enum MsgType {
    /// <summary>
    /// 占位
    /// </summary>
    [pbr::OriginalName("MSG_NONE")] MsgNone = 0,
    /// <summary>
    /// 玩家操作（客户端->服务器）
    /// </summary>
    [pbr::OriginalName("MSG_PLAYER_INPUT")] MsgPlayerInput = 1,
    /// <summary>
    /// 帧数据（服务器->客户端）
    /// </summary>
    [pbr::OriginalName("MSG_FRAME_DATA")] MsgFrameData = 2,
    /// <summary>
    /// 邮件推送
    /// </summary>
    [pbr::OriginalName("MSG_MAIL_PUSH")] MsgMailPush = 3,
    /// <summary>
    /// 活动结算推送
    /// </summary>
    [pbr::OriginalName("MSG_ACTIVITY_REWARD_PUSH")] MsgActivityRewardPush = 4,
    /// <summary>
    /// UDP 连接认证请求（客户端->GameServer，带 JWT token）
    /// </summary>
    [pbr::OriginalName("MSG_UDP_LOGIN_REQ")] MsgUdpLoginReq = 5,
    /// <summary>
    /// UDP 连接认证回复（GameServer->客户端）
    /// </summary>
    [pbr::OriginalName("MSG_UDP_LOGIN_ACK")] MsgUdpLoginAck = 6,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 消息信封：所有 UDP 消息统一包在这一层，首字段标识消息类型，payload 承载具体消息
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NetMsgEnvelope : pb::IMessage<NetMsgEnvelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NetMsgEnvelope> _parser = new pb::MessageParser<NetMsgEnvelope>(() => new NetMsgEnvelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NetMsgEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NetMsg.NetCommonReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMsgEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMsgEnvelope(NetMsgEnvelope other) : this() {
      msgType_ = other.msgType_;
      payload_ = other.payload_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NetMsgEnvelope Clone() {
      return new NetMsgEnvelope(this);
    }

    /// <summary>Field number for the "msg_type" field.</summary>
    public const int MsgTypeFieldNumber = 1;
    private global::NetMsg.MsgType msgType_ = global::NetMsg.MsgType.MsgNone;
    /// <summary>
    /// 消息类型（见 MsgType 枚举）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NetMsg.MsgType MsgType {
      get { return msgType_; }
      set {
        msgType_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 2;
    private pb::ByteString payload_ = pb::ByteString.Empty;
    /// <summary>
    /// 具体消息的 proto 序列化字节
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as NetMsgEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NetMsgEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MsgType != other.MsgType) return false;
      if (Payload != other.Payload) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MsgType != global::NetMsg.MsgType.MsgNone) hash ^= MsgType.GetHashCode();
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MsgType != global::NetMsg.MsgType.MsgNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MsgType != global::NetMsg.MsgType.MsgNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MsgType);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Payload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MsgType != global::NetMsg.MsgType.MsgNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MsgType);
      }
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NetMsgEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.MsgType != global::NetMsg.MsgType.MsgNone) {
        MsgType = other.MsgType;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MsgType = (global::NetMsg.MsgType) input.ReadEnum();
            break;
          }
          case 18: {
            Payload = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MsgType = (global::NetMsg.MsgType) input.ReadEnum();
            break;
          }
          case 18: {
            Payload = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
