
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum DUIGroup
    {
        /// <summary>
        /// 最底层
        /// </summary>
        Bottom1 = 1,
        Bottom2 = 2,
        Bottom3 = 3,
        Middle1 = 4,
        Middle2 = 5,
        Middle3 = 6,
        Top1 = 7,
        Top2 = 8,
        /// <summary>
        /// 最高层
        /// </summary>
        Top3 = 9,
    }

} 

