
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum DUIGroup
    {
        /// <summary>
        /// 最底层
        /// </summary>
        Bottom_1 = 1,
        Bottom_2 = 2,
        Bottom_3 = 3,
        Middle_1 = 4,
        Middle_2 = 5,
        Middle_3 = 6,
        Top_1 = 7,
        Top_2 = 8,
        /// <summary>
        /// 最高层
        /// </summary>
        Top_3 = 9,
    }

} 

