
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class DUIPanel : Luban.BeanBase
{
    public DUIPanel(ByteBuf _buf) 
    {
        Id = (DPnlId)_buf.ReadInt();
        Name = _buf.ReadString();
        Group = (DUIGroup)_buf.ReadInt();
        AllowMult = _buf.ReadBool();
        HideCovered = _buf.ReadBool();
    }

    public static DUIPanel DeserializeDUIPanel(ByteBuf _buf)
    {
        return new DUIPanel(_buf);
    }

    /// <summary>
    /// 界面id
    /// </summary>
    public readonly DPnlId Id;
    /// <summary>
    /// 界面名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 界面所属组
    /// </summary>
    public readonly DUIGroup Group;
    /// <summary>
    /// 是否允许多个界面实例
    /// </summary>
    public readonly bool AllowMult;
    /// <summary>
    /// 是否隐藏被覆盖的界面
    /// </summary>
    public readonly bool HideCovered;
   
    public const int __ID__ = -1452771572;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "group:" + Group + ","
        + "allowMult:" + AllowMult + ","
        + "hideCovered:" + HideCovered + ","
        + "}";
    }
}
}

