
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class DWeapon : Luban.BeanBase
{
    public DWeapon(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Interval = _buf.ReadFloat();
        BulletId = _buf.ReadInt();
        BulletSpeed = _buf.ReadInt();
        BulletSoundId = _buf.ReadInt();
    }

    public static DWeapon DeserializeDWeapon(ByteBuf _buf)
    {
        return new DWeapon(_buf);
    }

    /// <summary>
    /// 武器编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 攻击间隔
    /// </summary>
    public readonly float Interval;
    /// <summary>
    /// 子弹id
    /// </summary>
    public readonly int BulletId;
    /// <summary>
    /// 子弹速度
    /// </summary>
    public readonly int BulletSpeed;
    /// <summary>
    /// 子弹声音编号
    /// </summary>
    public readonly int BulletSoundId;
   
    public const int __ID__ = -1487246464;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "attack:" + Attack + ","
        + "interval:" + Interval + ","
        + "bulletId:" + BulletId + ","
        + "bulletSpeed:" + BulletSpeed + ","
        + "bulletSoundId:" + BulletSoundId + ","
        + "}";
    }
}
}

