
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbEntity
{
    private readonly System.Collections.Generic.Dictionary<int, DEntity> _dataMap;
    private readonly System.Collections.Generic.List<DEntity> _dataList;
    
    public TbEntity(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DEntity>(n);
        _dataList = new System.Collections.Generic.List<DEntity>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DEntity _v;
            _v = global::cfg.DEntity.DeserializeDEntity(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DEntity> DataMap => _dataMap;
    public System.Collections.Generic.List<DEntity> DataList => _dataList;

    public DEntity GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DEntity Get(int key) => _dataMap[key];
    public DEntity this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

