
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbThruster
{
    private readonly System.Collections.Generic.Dictionary<int, DThruster> _dataMap;
    private readonly System.Collections.Generic.List<DThruster> _dataList;
    
    public TbThruster(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, DThruster>(n);
        _dataList = new System.Collections.Generic.List<DThruster>(n);
        for(int i = n ; i > 0 ; --i)
        {
            DThruster _v;
            _v = global::cfg.DThruster.DeserializeDThruster(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DThruster> DataMap => _dataMap;
    public System.Collections.Generic.List<DThruster> DataList => _dataList;

    public DThruster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public DThruster Get(int key) => _dataMap[key];
    public DThruster this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

