org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=.xml, UnityServicesProjectConfiguration.json, aa/catalog.json, aa/settings.json
unityTemplateVersion=7
android.useAndroidX=true
android.enableJetifier=true
org.gradle.welcome=never
android.aapt2FromMavenOverride=/Users/wangshaowen/Downloads/2022.3.62f3/PlaybackEngines/AndroidPlayer/SDK/build-tools/34.0.0/aapt2